timestamp = 1645198528

[signatures]
anim_overlays = 10640
clientstate_choked_commands = 19760
clientstate_delta_ticks = 372
clientstate_last_outgoing_command = 19756
clientstate_net_channel = 156
convar_name_hash_table = 192760
dwClientState = 5816260
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19784
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 904
dwClientState_PlayerInfo = 21184
dwClientState_State = 264
dwClientState_ViewAngles = 19856
dwEntityList = 81596012
dwForceAttack = 52433792
dwForceAttack2 = 52433804
dwForceBackward = 52433708
dwForceForward = 52433840
dwForceJump = 86486416
dwForceLeft = 52433720
dwForceRight = 52433732
dwGameDir = 6465664
dwGameRulesProxy = 86957548
dwGetAllClasses = 14545276
dwGlobalVars = 5815496
dwGlowObjectManager = 87134816
dwInput = 86123584
dwInterfaceLinkList = 9863092
dwLocalPlayer = 14374364
dwMouseEnable = 14398184
dwMouseEnablePtr = 14398136
dwPlayerResource = 52426448
dwRadarBase = 86006756
dwSensitivity = 14397828
dwSensitivityPtr = 14397784
dwSetClanTag = 566080
dwViewMatrix = 81536900
dwWeaponTable = 86126344
dwWeaponTableIndex = 12908
dwYawPtr = 14397256
dwZoomSensitivityRatioPtr = 14422360
dwbSendPackets = 890050
dwppDirect3DDevice9 = 675920
find_hud_element = 663964144
force_update_spectator_glow = 3911770
interface_engine_cvar = 256492
is_c4_owner = 3965200
m_bDormant = 237
m_flSpawnTime = 66496
m_pStudioHdr = 10576
m_pitchClassPtr = 86007424
m_yawClassPtr = 14397256
model_ambient_min = 5828668
set_abs_angles = 1987376
set_abs_origin = 1986928

[netvars]
cs_gamerules_data = 0
m_ArmorValue = 71628
m_Collision = 800
m_CollisionGroup = 1140
m_Local = 12236
m_MoveType = 604
m_OriginalOwnerXuidHigh = 12756
m_OriginalOwnerXuidLow = 12752
m_SurvivalGameRuleDecisionTypes = 4904
m_SurvivalRules = 3328
m_aimPunchAngle = 12348
m_aimPunchAngleVel = 12360
m_angEyeAnglesX = 71632
m_angEyeAnglesY = 71636
m_bBombDefused = 10688
m_bBombPlanted = 2469
m_bBombTicking = 10640
m_bFreezePeriod = 32
m_bGunGameImmunity = 39312
m_bHasDefuser = 71644
m_bHasHelmet = 71616
m_bInReload = 12981
m_bIsDefusing = 39292
m_bIsQueuedMatchmaking = 116
m_bIsScoped = 39284
m_bIsValveDS = 124
m_bSpotted = 2365
m_bSpottedByMask = 2432
m_bStartedArming = 13312
m_bUseCustomAutoExposureMax = 2521
m_bUseCustomAutoExposureMin = 2520
m_bUseCustomBloomScale = 2522
m_clrRender = 112
m_dwBoneMatrix = 9896
m_fAccuracyPenalty = 13120
m_fFlags = 260
m_flC4Blow = 10656
m_flCustomAutoExposureMax = 2528
m_flCustomAutoExposureMin = 2524
m_flCustomBloomScale = 2532
m_flDefuseCountDown = 10684
m_flDefuseLength = 10680
m_flFallbackWear = 12768
m_flFlashDuration = 66672
m_flFlashMaxAlpha = 66668
m_flLastBoneSetupTime = 10536
m_flLowerBodyYawTarget = 39644
m_flNextAttack = 11648
m_flNextPrimaryAttack = 12872
m_flSimulationTime = 616
m_flTimerLength = 10660
m_hActiveWeapon = 12040
m_hBombDefuser = 10692
m_hMyWeapons = 11784
m_hObserverTarget = 13212
m_hOwner = 10716
m_hOwnerEntity = 332
m_hViewModel = 13064
m_iAccountID = 12248
m_iClip1 = 12916
m_iCompetitiveRanking = 6788
m_iCompetitiveWins = 7048
m_iCrosshairId = 71736
m_iDefaultFOV = 13116
m_iEntityQuality = 12220
m_iFOV = 12788
m_iFOVStart = 12792
m_iGlowIndex = 66696
m_iHealth = 256
m_iItemDefinitionIndex = 12218
m_iItemIDHigh = 12240
m_iMostRecentModelBoneCounter = 9872
m_iObserverMode = 13192
m_iShotsFired = 66528
m_iState = 12904
m_iTeamNum = 244
m_lifeState = 607
m_nBombSite = 10644
m_nFallbackPaintKit = 12760
m_nFallbackSeed = 12764
m_nFallbackStatTrak = 12772
m_nForceBone = 9868
m_nTickBase = 13376
m_nViewModelIndex = 10704
m_rgflCoordinateFrame = 1092
m_szCustomName = 12364
m_szLastPlaceName = 13764
m_thirdPersonViewAngles = 12776
m_vecOrigin = 312
m_vecVelocity = 276
m_vecViewOffset = 264
m_viewPunchAngle = 12336
m_zoomLevel = 13280
