timestamp = 1575969778

[signatures]
anim_overlays = 10624
clientstate_choked_commands = 19752
clientstate_delta_ticks = 372
clientstate_last_outgoing_command = 19748
clientstate_net_channel = 156
convar_name_hash_table = 192760
dwClientState = 5803428
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19776
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 904
dwClientState_PlayerInfo = 21176
dwClientState_State = 264
dwClientState_ViewAngles = 19848
dwEntityList = 80983852
dwForceAttack = 51826204
dwForceAttack2 = 51826216
dwForceBackward = 51826132
dwForceForward = 51826240
dwForceJump = 85847832
dwForceLeft = 51826120
dwForceRight = 51826156
dwGameDir = 6452464
dwGameRulesProxy = 86319612
dwGetAllClasses = 13950116
dwGlobalVars = 5802664
dwGlowObjectManager = 86495088
dwInput = 85485768
dwInterfaceLinkList = 9389044
dwLocalPlayer = 13793980
dwMouseEnable = 13817440
dwMouseEnablePtr = 13817392
dwPlayerResource = 51818860
dwRadarBase = 85394572
dwSensitivity = 13817084
dwSensitivityPtr = 13817040
dwSetClanTag = 563856
dwViewMatrix = 80924996
dwWeaponTable = 85488524
dwWeaponTableIndex = 12860
dwYawPtr = 13816512
dwZoomSensitivityRatioPtr = 13837536
dwbSendPackets = 864890
dwppDirect3DDevice9 = 679984
find_hud_element = 715568592
force_update_spectator_glow = 3767826
interface_engine_cvar = 256492
is_c4_owner = 3818064
m_bDormant = 237
m_flSpawnTime = 41824
m_pStudioHdr = 10572
m_pitchClassPtr = 85395240
m_yawClassPtr = 13816512
model_ambient_min = 5815748
set_abs_angles = 1895040
set_abs_origin = 1894592

[netvars]
cs_gamerules_data = 0
m_ArmorValue = 45928
m_Collision = 800
m_CollisionGroup = 1140
m_Local = 12220
m_MoveType = 604
m_OriginalOwnerXuidHigh = 12724
m_OriginalOwnerXuidLow = 12720
m_SurvivalGameRuleDecisionTypes = 4896
m_SurvivalRules = 3320
m_aimPunchAngle = 12332
m_aimPunchAngleVel = 12344
m_angEyeAnglesX = 45932
m_angEyeAnglesY = 45936
m_bBombPlanted = 2461
m_bFreezePeriod = 32
m_bGunGameImmunity = 14640
m_bHasDefuser = 45944
m_bHasHelmet = 45916
m_bInReload = 12933
m_bIsDefusing = 14620
m_bIsQueuedMatchmaking = 116
m_bIsScoped = 14612
m_bIsValveDS = 117
m_bSpotted = 2365
m_bSpottedByMask = 2432
m_bStartedArming = 13264
m_bUseCustomAutoExposureMax = 2521
m_bUseCustomAutoExposureMin = 2520
m_bUseCustomBloomScale = 2522
m_clrRender = 112
m_dwBoneMatrix = 9896
m_fAccuracyPenalty = 13072
m_fFlags = 260
m_flC4Blow = 10640
m_flCustomAutoExposureMax = 2528
m_flCustomAutoExposureMin = 2524
m_flCustomBloomScale = 2532
m_flDefuseCountDown = 10668
m_flDefuseLength = 10664
m_flFallbackWear = 12736
m_flFlashDuration = 42000
m_flFlashMaxAlpha = 41996
m_flLastBoneSetupTime = 10532
m_flLowerBodyYawTarget = 14972
m_flNextAttack = 11632
m_flNextPrimaryAttack = 12824
m_flSimulationTime = 616
m_flTimerLength = 10644
m_hActiveWeapon = 12024
m_hMyWeapons = 11768
m_hObserverTarget = 13192
m_hOwner = 10700
m_hOwnerEntity = 332
m_iAccountID = 12232
m_iClip1 = 12868
m_iCompetitiveRanking = 6788
m_iCompetitiveWins = 7048
m_iCrosshairId = 46036
m_iEntityQuality = 12204
m_iFOV = 12772
m_iFOVStart = 12776
m_iGlowIndex = 42024
m_iHealth = 256
m_iItemDefinitionIndex = 12202
m_iItemIDHigh = 12224
m_iMostRecentModelBoneCounter = 9872
m_iObserverMode = 13172
m_iShotsFired = 41856
m_iState = 12856
m_iTeamNum = 244
m_lifeState = 607
m_nFallbackPaintKit = 12728
m_nFallbackSeed = 12732
m_nFallbackStatTrak = 12740
m_nForceBone = 9868
m_nTickBase = 13356
m_rgflCoordinateFrame = 1092
m_szCustomName = 12348
m_szLastPlaceName = 13744
m_thirdPersonViewAngles = 12760
m_vecOrigin = 312
m_vecVelocity = 276
m_vecViewOffset = 264
m_viewPunchAngle = 12320
