timestamp = 1634378240

[signatures]
anim_overlays = 10640
clientstate_choked_commands = 19760
clientstate_delta_ticks = 372
clientstate_last_outgoing_command = 19756
clientstate_net_channel = 156
convar_name_hash_table = 192760
dwClientState = 5804012
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19784
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 904
dwClientState_PlayerInfo = 21184
dwClientState_State = 264
dwClientState_ViewAngles = 19856
dwEntityList = 81515980
dwForceAttack = 52353824
dwForceAttack2 = 52353836
dwForceBackward = 52353908
dwForceForward = 52353872
dwForceJump = 86406108
dwForceLeft = 52353896
dwForceRight = 52353776
dwGameDir = 6452992
dwGameRulesProxy = 86877884
dwGetAllClasses = 14465660
dwGlobalVars = 5803248
dwGlowObjectManager = 87055072
dwInput = 86043536
dwInterfaceLinkList = 9782084
dwLocalPlayer = 14300236
dwMouseEnable = 14323608
dwMouseEnablePtr = 14323560
dwPlayerResource = 52346480
dwRadarBase = 85926724
dwSensitivity = 14323252
dwSensitivityPtr = 14323208
dwSetClanTag = 565552
dwViewMatrix = 81456868
dwWeaponTable = 86046292
dwWeaponTableIndex = 12908
dwYawPtr = 14322680
dwZoomSensitivityRatioPtr = 14343832
dwbSendPackets = 883666
dwppDirect3DDevice9 = 684112
find_hud_element = 1559898304
force_update_spectator_glow = 3881370
interface_engine_cvar = 256492
is_c4_owner = 3934448
m_bDormant = 237
m_flSpawnTime = 66496
m_pStudioHdr = 10576
m_pitchClassPtr = 85927392
m_yawClassPtr = 14322680
model_ambient_min = 5816332
set_abs_angles = 1980352
set_abs_origin = 1979904

[netvars]
cs_gamerules_data = 0
m_ArmorValue = 70604
m_Collision = 800
m_CollisionGroup = 1140
m_Local = 12236
m_MoveType = 604
m_OriginalOwnerXuidHigh = 12756
m_OriginalOwnerXuidLow = 12752
m_SurvivalGameRuleDecisionTypes = 4904
m_SurvivalRules = 3328
m_aimPunchAngle = 12348
m_aimPunchAngleVel = 12360
m_angEyeAnglesX = 70608
m_angEyeAnglesY = 70612
m_bBombDefused = 10688
m_bBombPlanted = 2469
m_bBombTicking = 10640
m_bFreezePeriod = 32
m_bGunGameImmunity = 39312
m_bHasDefuser = 70620
m_bHasHelmet = 70592
m_bInReload = 12981
m_bIsDefusing = 39292
m_bIsQueuedMatchmaking = 116
m_bIsScoped = 39284
m_bIsValveDS = 124
m_bSpotted = 2365
m_bSpottedByMask = 2432
m_bStartedArming = 13312
m_bUseCustomAutoExposureMax = 2521
m_bUseCustomAutoExposureMin = 2520
m_bUseCustomBloomScale = 2522
m_clrRender = 112
m_dwBoneMatrix = 9896
m_fAccuracyPenalty = 13120
m_fFlags = 260
m_flC4Blow = 10656
m_flCustomAutoExposureMax = 2528
m_flCustomAutoExposureMin = 2524
m_flCustomBloomScale = 2532
m_flDefuseCountDown = 10684
m_flDefuseLength = 10680
m_flFallbackWear = 12768
m_flFlashDuration = 66672
m_flFlashMaxAlpha = 66668
m_flLastBoneSetupTime = 10536
m_flLowerBodyYawTarget = 39644
m_flNextAttack = 11648
m_flNextPrimaryAttack = 12872
m_flSimulationTime = 616
m_flTimerLength = 10660
m_hActiveWeapon = 12040
m_hBombDefuser = 10692
m_hMyWeapons = 11784
m_hObserverTarget = 13212
m_hOwner = 10716
m_hOwnerEntity = 332
m_hViewModel = 13064
m_iAccountID = 12248
m_iClip1 = 12916
m_iCompetitiveRanking = 6788
m_iCompetitiveWins = 7048
m_iCrosshairId = 70712
m_iDefaultFOV = 13116
m_iEntityQuality = 12220
m_iFOV = 12788
m_iFOVStart = 12792
m_iGlowIndex = 66696
m_iHealth = 256
m_iItemDefinitionIndex = 12218
m_iItemIDHigh = 12240
m_iMostRecentModelBoneCounter = 9872
m_iObserverMode = 13192
m_iShotsFired = 66528
m_iState = 12904
m_iTeamNum = 244
m_lifeState = 607
m_nBombSite = 10644
m_nFallbackPaintKit = 12760
m_nFallbackSeed = 12764
m_nFallbackStatTrak = 12772
m_nForceBone = 9868
m_nTickBase = 13376
m_nViewModelIndex = 10704
m_rgflCoordinateFrame = 1092
m_szCustomName = 12364
m_szLastPlaceName = 13764
m_thirdPersonViewAngles = 12776
m_vecOrigin = 312
m_vecVelocity = 276
m_vecViewOffset = 264
m_viewPunchAngle = 12336
m_zoomLevel = 13280
