# Wed, 28 Jun 2017 18:31:50 +0200
timestamp = 1498667510

[netvars]
m_ArmorValue = 45640
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14512
m_bHasDefuser = 45656
m_bHasHelmet = 45628
m_bInReload = 12869
m_bIsDefusing = 14500
m_bIsScoped = 14492
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12992
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41736
m_flFlashMaxAlpha = 41732
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hObserverTarget = 13184
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 45748
m_iEntityQuality = 12172
m_iFOVStart = 12760
m_iGlowIndex = 41760
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iObserverMode = 13164
m_iShotsFired = 41664
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13348
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13736
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304

[signatures]
dwClientState = 5911292
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19656
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 784
dwClientState_PlayerInfo = 21056
dwClientState_State = 264
dwClientState_ViewAngles = 19728
dwEntityList = 78161492
dwForceAttack = 49072648
dwForceAttack2 = 49072660
dwForceBackward = 49072696
dwForceForward = 49072732
dwForceJump = 82974184
dwForceLeft = 49072708
dwForceRight = 49072612
dwGameDir = 6560600
dwGameRulesProxy = 83410700
dwGetAllClasses = 83410912
dwGlobalVars = 5910528
dwGlowObjectManager = 83523168
dwInput = 82662008
dwInterfaceLinkList = 7247668
dwLocalPlayer = 11198460
dwMouseEnable = 11221088
dwMouseEnablePtr = 11221040
dwPlayerResource = 49065308
dwRadarBase = 82572108
dwSensitivity = 11220732
dwSensitivityPtr = 11220688
dwSetClanTag = 553744
dwViewMatrix = 78102708
dwWeaponTable = 82647056
dwWeaponTableIndex = 12912
dwYawPtr = 11220160
dwZoomSensitivityRatioPtr = 11240744
dwbSendPackets = 841018
dwppDirect3DDevice9 = 642880
m_pStudioHdr = 10556
