# Tue, 22 Aug 2017 20:01:05 +0200
timestamp = 1503424865

[netvars]
m_ArmorValue = 45608
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14480
m_bHasDefuser = 45624
m_bHasHelmet = 45596
m_bInReload = 12869
m_bIsDefusing = 14468
m_bIsScoped = 14460
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12976
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41704
m_flFlashMaxAlpha = 41700
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hObserverTarget = 13152
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 45716
m_iEntityQuality = 12172
m_iFOVStart = 12760
m_iGlowIndex = 41728
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iObserverMode = 13132
m_iShotsFired = 41632
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13316
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13704
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304

[signatures]
dwClientState = 5915444
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19656
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 784
dwClientState_PlayerInfo = 21056
dwClientState_State = 264
dwClientState_ViewAngles = 19728
dwEntityList = 78142124
dwForceAttack = 49053240
dwForceAttack2 = 49053252
dwForceBackward = 49053264
dwForceForward = 49053300
dwForceJump = 82954536
dwForceLeft = 49053276
dwForceRight = 49053336
dwGameDir = 6564816
dwGameRulesProxy = 83389548
dwGetAllClasses = 83389760
dwGlobalVars = 5914680
dwGlowObjectManager = 83501624
dwInput = 82642544
dwInterfaceLinkList = 7233172
dwLocalPlayer = 11176892
dwMouseEnable = 11199520
dwMouseEnablePtr = 11199472
dwPlayerResource = 49045948
dwRadarBase = 82552740
dwSensitivity = 11199164
dwSensitivityPtr = 11199120
dwSetClanTag = 543280
dwViewMatrix = 78083332
dwWeaponTable = 82645604
dwWeaponTableIndex = 12796
dwYawPtr = 11198592
dwZoomSensitivityRatioPtr = 11219176
dwbSendPackets = 830634
dwppDirect3DDevice9 = 642880
m_pStudioHdr = 10556
