timestamp = 1551187036

[signatures]
clientstate_choked_commands = 19752
clientstate_delta_ticks = 372
clientstate_last_outgoing_command = 19748
clientstate_net_channel = 156
convar_name_hash_table = 192760
dwClientState = 5815548
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19776
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 904
dwClientState_PlayerInfo = 21176
dwClientState_State = 264
dwClientState_ViewAngles = 19848
dwEntityList = 80588924
dwForceAttack = 51431296
dwForceAttack2 = 51431308
dwForceBackward = 51431224
dwForceForward = 51431332
dwForceJump = 85451316
dwForceLeft = 51431212
dwForceRight = 51431248
dwGameDir = 6496112
dwGameRulesProxy = 85919092
dwGetAllClasses = 13560412
dwGlobalVars = 5814784
dwGlowObjectManager = 86093736
dwInput = 85089808
dwInterfaceLinkList = 9079508
dwLocalPlayer = 13412020
dwMouseEnable = 13435392
dwMouseEnablePtr = 13435344
dwPlayerResource = 51423964
dwRadarBase = 84999612
dwSensitivity = 13435036
dwSensitivityPtr = 13434992
dwSetClanTag = 562848
dwViewMatrix = 80530068
dwWeaponTable = 85092564
dwWeaponTableIndex = 12860
dwYawPtr = 13434464
dwZoomSensitivityRatioPtr = 13455520
dwbSendPackets = 861002
dwppDirect3DDevice9 = 671680
force_update_spectator_glow = 3723986
interface_engine_cvar = 256492
is_c4_owner = 3773296
m_bDormant = 237
m_pStudioHdr = 10572
m_pitchClassPtr = 85000304
m_yawClassPtr = 13434464
model_ambient_min = 5827868
set_abs_angles = 1864320
set_abs_origin = 1863872

[netvars]
cs_gamerules_data = 0
m_ArmorValue = 45864
m_Collision = 796
m_CollisionGroup = 1140
m_Local = 12220
m_MoveType = 604
m_OriginalOwnerXuidHigh = 12724
m_OriginalOwnerXuidLow = 12720
m_SurvivalGameRuleDecisionTypes = 4888
m_SurvivalRules = 3312
m_aimPunchAngle = 12332
m_aimPunchAngleVel = 12344
m_angEyeAnglesX = 45868
m_angEyeAnglesY = 45872
m_bBombPlanted = 2461
m_bFreezePeriod = 32
m_bGunGameImmunity = 14632
m_bHasDefuser = 45880
m_bHasHelmet = 45852
m_bInReload = 12933
m_bIsDefusing = 14612
m_bIsQueuedMatchmaking = 116
m_bIsScoped = 14602
m_bIsValveDS = 117
m_bSpotted = 2365
m_bSpottedByMask = 2432
m_clrRender = 112
m_dwBoneMatrix = 9896
m_fAccuracyPenalty = 13060
m_fFlags = 260
m_flC4Blow = 10640
m_flDefuseCountDown = 10668
m_flDefuseLength = 10664
m_flFallbackWear = 12736
m_flFlashDuration = 41952
m_flFlashMaxAlpha = 41948
m_flLastBoneSetupTime = 10532
m_flLowerBodyYawTarget = 14964
m_flNextAttack = 11632
m_flNextPrimaryAttack = 12824
m_flSimulationTime = 616
m_flTimerLength = 10644
m_hActiveWeapon = 12024
m_hMyWeapons = 11768
m_hObserverTarget = 13192
m_hOwner = 10700
m_hOwnerEntity = 332
m_iAccountID = 12232
m_iClip1 = 12868
m_iCompetitiveRanking = 6788
m_iCompetitiveWins = 7048
m_iCrosshairId = 45972
m_iEntityQuality = 12204
m_iFOV = 12772
m_iFOVStart = 12776
m_iGlowIndex = 41976
m_iHealth = 256
m_iItemDefinitionIndex = 12202
m_iItemIDHigh = 12224
m_iMostRecentModelBoneCounter = 9872
m_iObserverMode = 13172
m_iShotsFired = 41840
m_iState = 12856
m_iTeamNum = 244
m_lifeState = 607
m_nFallbackPaintKit = 12728
m_nFallbackSeed = 12732
m_nFallbackStatTrak = 12740
m_nForceBone = 9868
m_nTickBase = 13356
m_rgflCoordinateFrame = 1092
m_szCustomName = 12348
m_szLastPlaceName = 13744
m_thirdPersonViewAngles = 12760
m_vecOrigin = 312
m_vecVelocity = 276
m_vecViewOffset = 264
m_viewPunchAngle = 12320
