# Thu, 19 Oct 2017 00:08:15 +0200
timestamp = 1508364495

[netvars]
m_ArmorValue = 45624
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14484
m_bHasDefuser = 45640
m_bHasHelmet = 45612
m_bInReload = 12869
m_bIsDefusing = 14472
m_bIsScoped = 14462
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12976
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41720
m_flFlashMaxAlpha = 41716
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hObserverTarget = 13152
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 45732
m_iEntityQuality = 12172
m_iFOVStart = 12760
m_iGlowIndex = 41744
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iObserverMode = 13132
m_iShotsFired = 41648
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13316
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13704
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304

[signatures]
dwClientState = 5919556
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19656
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 784
dwClientState_PlayerInfo = 21056
dwClientState_State = 264
dwClientState_ViewAngles = 19728
dwEntityList = 78172604
dwForceAttack = 49083708
dwForceAttack2 = 49083720
dwForceBackward = 49083840
dwForceForward = 49083780
dwForceJump = 82985068
dwForceLeft = 49083852
dwForceRight = 49083816
dwGameDir = 6568912
dwGameRulesProxy = 83420084
dwGetAllClasses = 83420296
dwGlobalVars = 5918792
dwGlowObjectManager = 83532808
dwInput = 82673024
dwInterfaceLinkList = 7258228
dwLocalPlayer = 11206012
dwMouseEnable = 11228640
dwMouseEnablePtr = 11228592
dwPlayerResource = 49076428
dwRadarBase = 82583220
dwSensitivity = 11228284
dwSensitivityPtr = 11228240
dwSetClanTag = 543024
dwViewMatrix = 78113812
dwWeaponTable = 82676084
dwWeaponTableIndex = 12796
dwYawPtr = 11227712
dwZoomSensitivityRatioPtr = 11248296
dwbSendPackets = 830506
dwppDirect3DDevice9 = 663360
m_pStudioHdr = 10556
