timestamp = 1554296346

[signatures]
clientstate_choked_commands = 19752
clientstate_delta_ticks = 372
clientstate_last_outgoing_command = 19748
clientstate_net_channel = 156
convar_name_hash_table = 192760
dwClientState = 5815548
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19776
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 904
dwClientState_PlayerInfo = 21176
dwClientState_State = 264
dwClientState_ViewAngles = 19848
dwEntityList = 80622812
dwForceAttack = 51465124
dwForceAttack2 = 51465136
dwForceBackward = 51465208
dwForceForward = 51465172
dwForceJump = 85485944
dwForceLeft = 51465196
dwForceRight = 51465232
dwGameDir = 6496112
dwGameRulesProxy = 85953716
dwGetAllClasses = 13593540
dwGlobalVars = 5814784
dwGlowObjectManager = 86128432
dwInput = 85124336
dwInterfaceLinkList = 9112100
dwLocalPlayer = 13444964
dwMouseEnable = 13468336
dwMouseEnablePtr = 13468288
dwPlayerResource = 51457852
dwRadarBase = 85033500
dwSensitivity = 13467980
dwSensitivityPtr = 13467936
dwSetClanTag = 562848
dwViewMatrix = 80563956
dwWeaponTable = 85127096
dwWeaponTableIndex = 12860
dwYawPtr = 13467408
dwZoomSensitivityRatioPtr = 13488464
dwbSendPackets = 861594
dwppDirect3DDevice9 = 679984
force_update_spectator_glow = 3727234
interface_engine_cvar = 256492
is_c4_owner = 3776624
m_bDormant = 237
m_pStudioHdr = 10572
m_pitchClassPtr = 85034192
m_yawClassPtr = 13467408
model_ambient_min = 5827868
set_abs_angles = 1866864
set_abs_origin = 1866416

[netvars]
cs_gamerules_data = 0
m_ArmorValue = 45864
m_Collision = 796
m_CollisionGroup = 1140
m_Local = 12220
m_MoveType = 604
m_OriginalOwnerXuidHigh = 12724
m_OriginalOwnerXuidLow = 12720
m_SurvivalGameRuleDecisionTypes = 4896
m_SurvivalRules = 3320
m_aimPunchAngle = 12332
m_aimPunchAngleVel = 12344
m_angEyeAnglesX = 45868
m_angEyeAnglesY = 45872
m_bBombPlanted = 2461
m_bFreezePeriod = 32
m_bGunGameImmunity = 14632
m_bHasDefuser = 45880
m_bHasHelmet = 45852
m_bInReload = 12933
m_bIsDefusing = 14612
m_bIsQueuedMatchmaking = 116
m_bIsScoped = 14602
m_bIsValveDS = 117
m_bSpotted = 2365
m_bSpottedByMask = 2432
m_bStartedArming = 13248
m_clrRender = 112
m_dwBoneMatrix = 9896
m_fAccuracyPenalty = 13060
m_fFlags = 260
m_flC4Blow = 10640
m_flDefuseCountDown = 10668
m_flDefuseLength = 10664
m_flFallbackWear = 12736
m_flFlashDuration = 41952
m_flFlashMaxAlpha = 41948
m_flLastBoneSetupTime = 10532
m_flLowerBodyYawTarget = 14964
m_flNextAttack = 11632
m_flNextPrimaryAttack = 12824
m_flSimulationTime = 616
m_flTimerLength = 10644
m_hActiveWeapon = 12024
m_hMyWeapons = 11768
m_hObserverTarget = 13192
m_hOwner = 10700
m_hOwnerEntity = 332
m_iAccountID = 12232
m_iClip1 = 12868
m_iCompetitiveRanking = 6788
m_iCompetitiveWins = 7048
m_iCrosshairId = 45972
m_iEntityQuality = 12204
m_iFOV = 12772
m_iFOVStart = 12776
m_iGlowIndex = 41976
m_iHealth = 256
m_iItemDefinitionIndex = 12202
m_iItemIDHigh = 12224
m_iMostRecentModelBoneCounter = 9872
m_iObserverMode = 13172
m_iShotsFired = 41840
m_iState = 12856
m_iTeamNum = 244
m_lifeState = 607
m_nFallbackPaintKit = 12728
m_nFallbackSeed = 12732
m_nFallbackStatTrak = 12740
m_nForceBone = 9868
m_nTickBase = 13356
m_rgflCoordinateFrame = 1092
m_szCustomName = 12348
m_szLastPlaceName = 13744
m_thirdPersonViewAngles = 12760
m_vecOrigin = 312
m_vecVelocity = 276
m_vecViewOffset = 264
m_viewPunchAngle = 12320
